/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontend;

import backend.RealizarExperimento;
import java.util.List;
import org.bson.Document;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author PC
 */
public class GraficaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form IntroducciónJPanel
     */
    private XYSeriesCollection dataset;
    /**
     * Creates new form IntroducciónJPanel
     */
    public GraficaJPanel() {
        initComponents();
         initChart();
    }
     private void initChart() {
    dataset = new XYSeriesCollection();
    JFreeChart chart = ChartFactory.createXYLineChart(
            "Caída libre",    // Título del gráfico
            "Tiempo (s)",     // Etiqueta del eje X
            "Altura (m)",     // Etiqueta del eje Y
            dataset,           // Datos
            PlotOrientation.VERTICAL,
            true,              // Incluir leyenda
            true,
            false
    );

    ChartPanel chartPanel = new ChartPanel(chart);
    chartPanel.setPreferredSize(new java.awt.Dimension(515, 340));

    jPanelGrafica.setLayout(new java.awt.BorderLayout());
    jPanelGrafica.add(chartPanel, java.awt.BorderLayout.CENTER);

    // Obtener los datos de la base de datos y agregarlos a la gráfica
    RealizarExperimento experimento = new RealizarExperimento(0, 0); // Puedes crear una instancia de RealizarExperimento con valores temporales
    List<Document> datosFiltrados = experimento.consultarDatos();

    XYSeries series = new XYSeries("Datos de la base de datos");
    for (Document dato : datosFiltrados) {
        double tiempo = dato.getDouble("tiempo");
        double altura = dato.getDouble("altura");
        series.add(tiempo, altura);
    }
    dataset.addSeries(series);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanelGrafica = new javax.swing.JPanel();

        jLabel1.setFont(new java.awt.Font("Roboto", 3, 18)); // NOI18N
        jLabel1.setText("GRÁFICA");

        jPanelGrafica.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelGraficaLayout = new javax.swing.GroupLayout(jPanelGrafica);
        jPanelGrafica.setLayout(jPanelGraficaLayout);
        jPanelGraficaLayout.setHorizontalGroup(
            jPanelGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelGraficaLayout.setVerticalGroup(
            jPanelGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 362, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(250, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(246, 246, 246))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelGrafica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelGrafica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelGrafica;
    // End of variables declaration//GEN-END:variables
}
