/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import backend.RealizarExperimento;
import java.util.List;
import org.bson.Document;

/**
 *
 * @author PC
 */
public class MenuJFrame extends javax.swing.JFrame {

    private javax.swing.JPanel IntroduccionJPanel;

    /**
     * Creates new form MenuJFrame
     */
    public MenuJFrame() {

        initComponents();
        IntroduccionJPanel jpanelIntroduccion = new IntroduccionJPanel();

        jpanelIntroduccion.setSize(jPanelGeneral.getSize());
        jpanelIntroduccion.setLocation(0, 0);

        jPanelGeneral.removeAll();
        jPanelGeneral.add(jpanelIntroduccion);
        jPanelGeneral.revalidate();
        jPanelGeneral.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonSalir = new javax.swing.JButton();
        jButtonIntroduccion = new javax.swing.JButton();
        jButtonExperimento = new javax.swing.JButton();
        jButtonDatosAlmacenados = new javax.swing.JButton();
        jButtonVaciar = new javax.swing.JButton();
        jButtonGrafica = new javax.swing.JButton();
        jPanelGeneral = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon("./src/main/java/resources/fondo.png"));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 180, 220));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSalir.setBackground(new java.awt.Color(204, 0, 51));
        jButtonSalir.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setText("SALIR");
        jButtonSalir.setBorder(null);
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 0, 114, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 570, -1));

        jButtonIntroduccion.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jButtonIntroduccion.setForeground(new java.awt.Color(255, 255, 255));
        jButtonIntroduccion.setText("Introducción");
        jButtonIntroduccion.setBorder(null);
        jButtonIntroduccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIntroduccionActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIntroduccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 180, 40));

        jButtonExperimento.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jButtonExperimento.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExperimento.setText("Realizar Experimento");
        jButtonExperimento.setBorder(null);
        jButtonExperimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExperimentoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExperimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 180, 40));

        jButtonDatosAlmacenados.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jButtonDatosAlmacenados.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDatosAlmacenados.setText("Ver Datos Almacenados");
        jButtonDatosAlmacenados.setBorder(null);
        jButtonDatosAlmacenados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDatosAlmacenadosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDatosAlmacenados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 180, 40));

        jButtonVaciar.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jButtonVaciar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVaciar.setText("Vaciar Datos");
        jButtonVaciar.setBorder(null);
        jButtonVaciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVaciarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVaciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 180, 40));

        jButtonGrafica.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jButtonGrafica.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGrafica.setText("Mostrar Gráfica");
        jButtonGrafica.setBorder(null);
        jButtonGrafica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGraficaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGrafica, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 180, 40));

        jPanelGeneral.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelGeneralLayout = new javax.swing.GroupLayout(jPanelGeneral);
        jPanelGeneral.setLayout(jPanelGeneralLayout);
        jPanelGeneralLayout.setHorizontalGroup(
            jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );
        jPanelGeneralLayout.setVerticalGroup(
            jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 570, 420));

        jLabelTitulo.setFont(new java.awt.Font("Roboto", 3, 18)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("MENÚ");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonGraficaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGraficaActionPerformed
        GraficaJPanel jpanelGrafica = new GraficaJPanel();

        jpanelGrafica.setSize(jPanelGeneral.getSize());
        jpanelGrafica.setLocation(0, 0);

        jPanelGeneral.removeAll();
        jPanelGeneral.add(jpanelGrafica);
        jPanelGeneral.revalidate();
        jPanelGeneral.repaint();
    }//GEN-LAST:event_jButtonGraficaActionPerformed

    private void jButtonVaciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVaciarActionPerformed
        VaciarJPanel jpanelVaciar = new VaciarJPanel();

        jpanelVaciar.setSize(jPanelGeneral.getSize());
        jpanelVaciar.setLocation(0, 0);

        jPanelGeneral.removeAll();
        jPanelGeneral.add(jpanelVaciar);
        jPanelGeneral.revalidate();
        jPanelGeneral.repaint();
    }//GEN-LAST:event_jButtonVaciarActionPerformed

    private void jButtonDatosAlmacenadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDatosAlmacenadosActionPerformed
        List<Document> calculos = new RealizarExperimento(0,0).consultarDatos();

        DatosAlmacenadosJPanel jpanelDatosAlmacenados = new DatosAlmacenadosJPanel(calculos);

        jpanelDatosAlmacenados.setSize(jPanelGeneral.getSize());
        jpanelDatosAlmacenados.setLocation(0, 0);

        jPanelGeneral.removeAll();
        jPanelGeneral.add(jpanelDatosAlmacenados);
        jPanelGeneral.revalidate();
        jPanelGeneral.repaint();
    }//GEN-LAST:event_jButtonDatosAlmacenadosActionPerformed

    private void jButtonExperimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExperimentoActionPerformed
        ExperimentoJPanel jpanelExperimento = new ExperimentoJPanel();

        jpanelExperimento.setSize(jPanelGeneral.getSize());
        jpanelExperimento.setLocation(0, 0);

        jPanelGeneral.removeAll();
        jPanelGeneral.add(jpanelExperimento);
        jPanelGeneral.revalidate();
        jPanelGeneral.repaint();
    }//GEN-LAST:event_jButtonExperimentoActionPerformed

    private void jButtonIntroduccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIntroduccionActionPerformed
        IntroduccionJPanel jpanelIntroduccion = new IntroduccionJPanel();

        jpanelIntroduccion.setSize(jPanelGeneral.getSize());
        jpanelIntroduccion.setLocation(0, 0);

        jPanelGeneral.removeAll();
        jPanelGeneral.add(jpanelIntroduccion);
        jPanelGeneral.revalidate();
        jPanelGeneral.repaint();
    }//GEN-LAST:event_jButtonIntroduccionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDatosAlmacenados;
    private javax.swing.JButton jButtonExperimento;
    private javax.swing.JButton jButtonGrafica;
    private javax.swing.JButton jButtonIntroduccion;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonVaciar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelGeneral;
    // End of variables declaration//GEN-END:variables
}
