/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontend;

import backend.RealizarExperimento;
import com.mongodb.client.MongoClient;
import com.mongodb.client.MongoClients;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import org.bson.Document;

/**
 *
 * @author PC
 */
public class VaciarJPanel extends javax.swing.JPanel {

    /**
     * Creates new form IntroducciónJPanel
     */
     public VaciarJPanel() {
        initComponents();
    
    RealizarExperimento exp1 = new RealizarExperimento(0,0);
   try {
        // Establece la conexión a MongoDB
        MongoClient mongoClient = MongoClients.create("mongodb://localhost:27017");

        // Selecciona la base de datos y la colección
        MongoDatabase database = mongoClient.getDatabase("Objetos");
        MongoCollection<Document> areasCollection = database.getCollection("calculo");

        // Consulta para verificar si existen áreas de tipo círculo
        long count = areasCollection.countDocuments(new Document ("tipo","Objeto"));

        if (count > 0) {
            jLabelEliminar.setText("Se han eliminado los datos");  
            exp1.vaciarDatos();
        } else{
            jLabelEliminar.setText("No hay datos que eliminar"); 
        }
        mongoClient.close();
    } catch (Exception e) {
        e.printStackTrace();
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelEliminar = new javax.swing.JLabel();

        jLabelEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(188, Short.MAX_VALUE)
                .addComponent(jLabelEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabelEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(214, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelEliminar;
    // End of variables declaration//GEN-END:variables
}
